# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch

exec-once = yad --text="\n<span font='72' weight='bold'>TURN ON SECURITY</span>\n" --text-align=center --title="REMINDER" --button="OK":0 --width=900 --height=400 --center --on-top --fixed --undecorated
