-- Decoration settings. https://wiki.hypr.land/Configuring/Core/Config-options/#decoration
-- Animations live in UserAnimations.lua.

-- Colours generated by wallust (~/.config/wallust/templates/colors-hyprland.lua
-- renders to ~/.config/hypr/wallust/wallust-hyprland.lua on every wallpaper
-- change; Hyprland reloads automatically). If the file is missing - a fresh
-- machine before initial-boot.sh has run wallust - fall back to the palette
-- copy.sh seeds, so the config still loads.
local ok, c = pcall(require, "wallust.wallust-hyprland")
if not ok or type(c) ~= "table" then
    c = { color0 = "rgb(474D4D)", color10 = "rgb(033530)", color12 = "rgb(067263)", color15 = "rgb(7BD3C6)" }
end

hl.config({
    general = {
        border_size = 1,
        gaps_in     = 6,
        -- top right bottom left - only the top is tightened, to sit closer under
        -- the bar. Gaps between windows are gaps_in and are deliberately unchanged.
        gaps_out    = { top = 0, right = 12, bottom = 12, left = 12 },
        col = {
            active_border   = c.color12,
            inactive_border = c.color10,
        },
    },

    decoration = {
        rounding = 0,
        active_opacity     = 1.0,
        inactive_opacity   = 1.0,
        fullscreen_opacity = 1.0,
        dim_inactive = false,
        dim_strength = 0.1,
        dim_special  = 0.8,
        shadow = {
            enabled        = true,
            range          = 3,
            render_power   = 1,
            color          = c.color12,
            color_inactive = c.color10,
        },
        blur = {
            enabled = true,
            size    = 6,
            passes  = 2,
            ignore_opacity    = true,
            new_optimizations = true,
            special = true,
            popups  = true,
        },
    },

    group = {
        col = {
            border_active = c.color15,
        },
        groupbar = {
            col = {
                active = c.color0,
            },
        },
    },
})
