# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules
# This file will not be modified during dotfiles updates

windowrule = match:class ^(com.gabm.satty)$, float 1

# Float all JetBrains windows, then tile back the main editor
windowrule = match:class (jetbrains-.+), float 1
windowrule = match:class (jetbrains-.+) title (.*\[~/.*), tile 1
