#!/bin/bash
# Diagnostic script to check what went wrong with the installation

# Set colors
OK="$(tput setaf 2)[OK]$(tput sgr0)"
ERROR="$(tput setaf 1)[ERROR]$(tput sgr0)"
NOTE="$(tput setaf 3)[NOTE]$(tput sgr0)"
INFO="$(tput setaf 4)[INFO]$(tput sgr0)"
WARN="$(tput setaf 1)[WARN]$(tput sgr0)"
RESET="$(tput sgr0)"

printf "\n${NOTE} Running diagnostic checks...\n\n"

# Check if copy logs exist
printf "${INFO} Checking if dotfiles installation was attempted...\n"
if [ -d ~/Documents/Arch-Hyprland/Install-Logs ]; then
    if ls ~/Documents/Arch-Hyprland/Install-Logs/dotfiles-copy-*.log 1> /dev/null 2>&1; then
        printf "  ${OK} Dotfiles copy log found\n"
        latest_log=$(ls -t ~/Documents/Arch-Hyprland/Install-Logs/dotfiles-copy-*.log 2>/dev/null | head -1)
        printf "  ${INFO} Latest log: $latest_log\n"
        if [ -f "$latest_log" ]; then
            printf "  ${INFO} Last 10 lines of copy log:\n"
            tail -10 "$latest_log" | sed 's/^/    /'
        fi
    else
        printf "  ${WARN} No dotfiles copy log found (installation may not have run)\n"
    fi
else
    printf "  ${WARN} Install-Logs directory not found\n"
fi

# Check if running the default Hyprland config
printf "\n${INFO} Checking Hyprland configuration...\n"
if [ -f ~/.config/hypr/hyprland.conf ]; then
    if grep -q "autogenerated" ~/.config/hypr/hyprland.conf 2>/dev/null; then
        printf "  ${ERROR} Using DEFAULT autogenerated Hyprland config (PROBLEM FOUND)\n"
        printf "  ${NOTE} The custom dotfiles were NOT copied properly\n"
    else
        printf "  ${OK} Using custom Hyprland config\n"
    fi
else
    printf "  ${ERROR} hyprland.conf not found at all\n"
fi

# Check how many directories in ~/.config
printf "\n${INFO} Checking ~/.config directories...\n"
config_count=$(ls -d ~/.config/*/ 2>/dev/null | wc -l)
printf "  ${INFO} Found $config_count directories in ~/.config\n"
if [ "$config_count" -lt 15 ]; then
    printf "  ${WARN} Only $config_count directories (expected 15+). Custom dotfiles likely NOT copied.\n"
    printf "  ${INFO} Directories found: $(ls -d ~/.config/*/ 2>/dev/null | xargs -n1 basename | tr '\n' ' ')\n"
else
    printf "  ${OK} Found $config_count directories (looks good)\n"
fi

# Check if custom config sources exist
printf "\n${INFO} Checking critical custom directories...\n"
if [ -d ~/.config/hypr/configs ]; then
    printf "  ${OK} ~/.config/hypr/configs exists\n"
else
    printf "  ${ERROR} ~/.config/hypr/configs MISSING (custom config not installed)\n"
fi

if [ -d ~/.config/quickshell ]; then
    printf "  ${OK} ~/.config/quickshell exists\n"
else
    printf "  ${ERROR} ~/.config/quickshell MISSING (custom bar not installed)\n"
fi

if [ -d ~/.config/wlogout ]; then
    printf "  ${OK} ~/.config/wlogout exists\n"
else
    printf "  ${ERROR} ~/.config/wlogout MISSING\n"
fi

if [ -d ~/.config/wallust ]; then
    printf "  ${OK} ~/.config/wallust exists\n"
else
    printf "  ${ERROR} ~/.config/wallust MISSING\n"
fi

# Check if installation directory is complete
printf "\n${INFO} Checking Arch-Hyprland installation directory...\n"
if [ -d ~/Documents/Arch-Hyprland ]; then
    printf "  ${OK} ~/Documents/Arch-Hyprland exists\n"
    if [ -d ~/Documents/Arch-Hyprland/Hyprland-Dots ]; then
        printf "  ${OK} Hyprland-Dots subdirectory exists\n"
        if [ -f ~/Documents/Arch-Hyprland/Hyprland-Dots/copy.sh ]; then
            printf "  ${OK} copy.sh exists in Hyprland-Dots\n"
        else
            printf "  ${ERROR} copy.sh NOT found in Hyprland-Dots\n"
        fi
    else
        printf "  ${ERROR} Hyprland-Dots subdirectory MISSING (this is the problem!)\n"
        printf "  ${NOTE} The installation cannot work without this directory\n"
    fi
else
    printf "  ${ERROR} ~/Documents/Arch-Hyprland directory not found\n"
fi

# Check essential packages
printf "\n${INFO} Checking essential packages...\n"
essential_packages=(
    "hyprpolkitagent"
    "swaync"
    "xdg-desktop-portal-hyprland"
    "quickshell"
    "foot"
    "hyprsunset"
    "wireguard-tools"
)

missing_packages=()
for pkg in "${essential_packages[@]}"; do
    if pacman -Qi "$pkg" &>/dev/null; then
        printf "  ${OK} $pkg is installed\n"
    else
        printf "  ${ERROR} $pkg is MISSING\n"
        missing_packages+=("$pkg")
    fi
done

# Check pokefetch scripts
printf "\n${INFO} Checking pokefetch scripts...\n"
if [ -f ~/pokefetch_perfect ]; then
    printf "  ${OK} ~/pokefetch_perfect exists\n"
else
    printf "  ${ERROR} ~/pokefetch_perfect MISSING\n"
fi

if [ -f ~/.local/bin/pokefetch-merge ]; then
    printf "  ${OK} ~/.local/bin/pokefetch-merge exists\n"
else
    printf "  ${ERROR} ~/.local/bin/pokefetch-merge MISSING\n"
fi

# Check if SDDM is enabled
printf "\n${INFO} Checking login manager...\n"
if systemctl is-enabled sddm &>/dev/null; then
    printf "  ${OK} SDDM is enabled\n"
else
    printf "  ${WARN} SDDM is NOT enabled\n"
fi

# Summary
printf "\n${NOTE} ========== SUMMARY ==========\n"
if [ ${#missing_packages[@]} -gt 0 ]; then
    printf "${ERROR} Missing packages found: ${missing_packages[*]}\n"
    printf "${INFO} To install missing packages, run:\n"
    printf "  yay -S ${missing_packages[*]}\n\n"
fi

if grep -q "autogenerated" ~/.config/hypr/hyprland.conf 2>/dev/null; then
    printf "\n${WARN} ========== FIX REQUIRED ==========\n"
    printf "${INFO} Your dotfiles were not copied. To fix this:\n\n"
    printf "1. Run the copy script manually:\n"
    printf "   cd ~/Documents/Arch-Hyprland/Hyprland-Dots\n"
    printf "   chmod +x copy.sh\n"
    printf "   ./copy.sh\n\n"
    printf "2. Restart Hyprland:\n"
    printf "   hyprctl dispatch exit\n\n"
    printf "   (or reboot your system)\n"
else
    printf "${OK} Configuration looks good!\n"
fi

printf "\n"
