pragma Singleton
import QtQuick
import Quickshell.Io

QtObject {
    id: theme

    // ------------------------------------------------------------------
    //  Palette
    // ------------------------------------------------------------------
    //  Generated by wallust from the current wallpaper into
    //  ~/.config/quickshell/bar/wallust-colors.json
    //  (template: ~/.config/wallust/templates/bar-colors.json,
    //   wired up in wallust.toml as `bar.template`).
    //
    //  The literals below are the sovietpunk palette and serve as
    //  fallbacks only - if the generated file is missing or malformed
    //  the bar still renders in the right family instead of going blank.
    //
    //  Design rule for this bar: it is MONOCHROME. Widgets are told
    //  apart by brightness and by their text label, never by hue,
    //  because the desktop it sits on is a two-hue composition and any
    //  stray hue becomes the loudest thing on screen. Hue is reserved
    //  for states that actually want your attention - see colAlert.
    // ------------------------------------------------------------------

    property color palBg: "#262625"      // warm near-black, matches window gaps
    property color palFg: "#E8C4C0"      // warm rose, primary values
    property color palBright: "#D6A29C"  // emphasis
    property color palDim: "#96716D"     // labels, secondary info
    property color palMuted: "#524B47"   // separators, inactive
    property color palFaint: "#4C4C4B"   // hairlines
    property color palAccent: "#D6A29C"  // active / connected
    property color palAlert: "#BE564A"   // needs attention
    property color palWarn: "#8E4137"    // degraded or unknown state
    property color palBorder: "#59302D"  // popup borders

    // ------------------------------------------------------------------
    //  Readability floor
    // ------------------------------------------------------------------
    //  wallust's dark slots (color0, color5, color8) are near-black by
    //  nature. Used as text on a bar that has no background of its own,
    //  they measured 2.1:1 against the wallpaper - unreadable. Raising a
    //  colour's HSL lightness to a floor keeps wallust's hue and
    //  saturation while guaranteeing the contrast holds for ANY wallpaper,
    //  which hardcoding lifted hexes would not.
    //
    //  Floors were chosen so each role clears WCAG AA (4.5:1) against the
    //  brightest tile of the current wallpaper's top strip.
    function atLeast(c, minLightness) {
        if (c.hslLightness >= minLightness)
            return c
        return Qt.hsla(c.hslHue, c.hslSaturation, minLightness, c.a)
    }

    function applyPalette(text) {
        if (!text || text.length === 0)
            return
        try {
            var j = JSON.parse(text)
            if (j.bg)     theme.palBg     = j.bg
            if (j.fg)     theme.palFg     = j.fg
            if (j.bright) theme.palBright = j.bright
            if (j.dim)    theme.palDim    = j.dim
            if (j.muted)  theme.palMuted  = j.muted
            if (j.faint)  theme.palFaint  = j.faint
            if (j.accent) theme.palAccent = j.accent
            if (j.alert)  theme.palAlert  = j.alert
            if (j.warn)   theme.palWarn   = j.warn
            if (j.border) theme.palBorder = j.border
        } catch (e) {
            // Keep the fallbacks rather than rendering an uncoloured bar.
            console.warn("Theme: could not parse wallust-colors.json:", e)
        }
    }

    // wallust rewrites the file in place, so a change notification can
    // arrive mid-write and yield truncated JSON. Debounce before parsing.
    property Timer paletteDebounce: Timer {
        interval: 80
        repeat: false
        onTriggered: theme.applyPalette(theme.paletteFile.text())
    }

    property FileView paletteFile: FileView {
        path: Qt.resolvedUrl("wallust-colors.json")
        watchChanges: true
        onFileChanged: {
            reload()
            theme.paletteDebounce.restart()
        }
        onLoadedChanged: if (loaded) theme.applyPalette(text())
    }

    // ------------------------------------------------------------------
    //  Neutral roles
    // ------------------------------------------------------------------
    //  Most of the bar is deliberately colourless: white where a widget is
    //  active or carries a reading, grey where it is idle. Only a handful of
    //  things are allowed hue, because hue means something there - the window
    //  title, the notification bell, the weather, the VPN, the power menu.
    //
    //  These keep a whisper of the wallpaper's hue (so the bar never looks
    //  like it belongs to a different desktop) but drop almost all of the
    //  saturation.
    function desat(c, keepSaturation, lightness) {
        return Qt.hsla(c.hslHue, c.hslSaturation * keepSaturation, lightness, c.a)
    }

    readonly property color colWhite: desat(palFg, 0.12, 0.95)
    readonly property color colGrey: desat(palFg, 0.08, 0.62)

    // ------------------------------------------------------------------
    //  Semantic roles - prefer these in new widgets
    // ------------------------------------------------------------------

    readonly property color colBg: palBg
    readonly property color colBgTransparent: "transparent"
    //  60% transparent, i.e. a 40% wash of the background colour sitting
    //  under the compositor blur. Steadies the text over busy parts of the
    //  wallpaper while still reading as see-through rather than a solid bar.
    readonly property color colBgWash: Qt.rgba(palBg.r, palBg.g, palBg.b, 0.40)

    //  Text roles are floored for legibility. colSeparator deliberately is
    //  NOT: WCAG applies to text, and the "│" dividers are decoration that
    //  should stay quiet rather than compete with the readings.
    readonly property color colLabel: colGrey                 // "CPU", "MEM"
    readonly property color colValue: colWhite                // 17%, 9.25G
    readonly property color colFg: palFg
    readonly property color colBright: palBright
    readonly property color colDim: atLeast(palDim, 0.59)
    readonly property color colMuted: atLeast(palMuted, 0.57)
    readonly property color colFaint: atLeast(palFaint, 0.56)
    readonly property color colSeparator: palMuted            // decoration, unfloored
    readonly property color colBorder: palBorder

    readonly property color colAccent: palAccent  // active, connected, on
    //  Floored to 0.62 rather than to AAA: pushing the alert hue any lighter
    //  washes it out until it no longer reads as "coloured", which is the
    //  entire job it has on a monochrome bar.
    readonly property color colAlert: atLeast(palAlert, 0.62)
    readonly property color colWarn: palWarn      // state unknown / degraded
    readonly property color colOnAlert: palBg     // text sitting on an alert fill

    // The bar has no background of its own (see shell.qml), so text cannot
    // rely on a surface for contrast and carries its own dark outline. This
    // replaces the old same-colour halo, which added no contrast and only
    // faked extra weight while smearing the glyph edges.
    readonly property color colTextShadow: Qt.rgba(0, 0, 0, 0.55)

    // ------------------------------------------------------------------
    //  Per-widget roles
    // ------------------------------------------------------------------
    //  All of these deliberately collapse onto the ramp above. They stay
    //  as named properties so a widget can be re-tinted in one place if
    //  it ever earns its own emphasis - but the default is: no hue.

    readonly property color colClock: palFg
    readonly property color colCpu: colGrey
    readonly property color colMem: colGrey
    readonly property color colDisk: colGrey
    readonly property color colVol: colWhite
    readonly property color colNetwork: colWhite
    readonly property color colBluetooth: colWhite
    readonly property color colWindow: colDim     // window title is secondary info
    readonly property color colKernel: colDim

    //  Per-area treatment, picked by eye from the comparison:
    //    workspaces      -> variant E (near-white active, light grey inactive)
    //    window title    -> variant A (kept the warm dim it already had)
    //    bell + clock    -> variant C (values lifted to near-white warm)
    //  Expressed as lightness floors so they still track the wallpaper.
    readonly property color colWorkspaceActive: colWhite
    readonly property color colWorkspaceInactive: colGrey

    // Centre group. The clock and city are white; the bell keeps its own
    // states (grey idle, alert on, warn when dunstctl cannot be reached).
    readonly property color colCenter: colWhite
    readonly property color colCenterMuted: colGrey

    // Unread badges: an unread message is an attention state, so it gets
    // the alert hue rather than a brand colour that would fight the rice.
    readonly property color colSlack: palAlert
    readonly property color colWhatsapp: palAlert

    // Font
    readonly property string fontFamily: "Terminess Nerd Font"
    readonly property int fontSize: 24
}
