pragma Singleton
import QtQuick
import Quickshell.Io

QtObject {
    id: theme

    // ------------------------------------------------------------------
    //  Palette
    // ------------------------------------------------------------------
    //  Generated by wallust from the current wallpaper into
    //  ~/.config/quickshell/bar/wallust-colors.json
    //  (template: ~/.config/wallust/templates/bar-colors.json,
    //   wired up in wallust.toml as `bar.template`).
    //
    //  The literals below are the sovietpunk palette and serve as
    //  fallbacks only - if the generated file is missing or malformed
    //  the bar still renders in the right family instead of going blank.
    //
    //  Design rule for this bar: it is MONOCHROME. Widgets are told
    //  apart by brightness and by their text label, never by hue,
    //  because the desktop it sits on is a two-hue composition and any
    //  stray hue becomes the loudest thing on screen. Hue is reserved
    //  for states that actually want your attention - see colAlert.
    // ------------------------------------------------------------------

    property color palBg: "#262625"      // warm near-black, matches window gaps
    property color palFg: "#E8C4C0"      // warm rose, primary values
    property color palBright: "#D6A29C"  // emphasis
    property color palDim: "#96716D"     // labels, secondary info
    property color palMuted: "#524B47"   // separators, inactive
    property color palFaint: "#4C4C4B"   // hairlines
    property color palAccent: "#D6A29C"  // active / connected
    property color palAlert: "#BE564A"   // needs attention
    property color palWarn: "#8E4137"    // degraded or unknown state
    property color palBorder: "#59302D"  // popup borders

    function applyPalette(text) {
        if (!text || text.length === 0)
            return
        try {
            var j = JSON.parse(text)
            if (j.bg)     theme.palBg     = j.bg
            if (j.fg)     theme.palFg     = j.fg
            if (j.bright) theme.palBright = j.bright
            if (j.dim)    theme.palDim    = j.dim
            if (j.muted)  theme.palMuted  = j.muted
            if (j.faint)  theme.palFaint  = j.faint
            if (j.accent) theme.palAccent = j.accent
            if (j.alert)  theme.palAlert  = j.alert
            if (j.warn)   theme.palWarn   = j.warn
            if (j.border) theme.palBorder = j.border
        } catch (e) {
            // Keep the fallbacks rather than rendering an uncoloured bar.
            console.warn("Theme: could not parse wallust-colors.json:", e)
        }
    }

    // wallust rewrites the file in place, so a change notification can
    // arrive mid-write and yield truncated JSON. Debounce before parsing.
    property Timer paletteDebounce: Timer {
        interval: 80
        repeat: false
        onTriggered: theme.applyPalette(theme.paletteFile.text())
    }

    property FileView paletteFile: FileView {
        path: Qt.resolvedUrl("wallust-colors.json")
        watchChanges: true
        onFileChanged: {
            reload()
            theme.paletteDebounce.restart()
        }
        onLoadedChanged: if (loaded) theme.applyPalette(text())
    }

    // ------------------------------------------------------------------
    //  Semantic roles - prefer these in new widgets
    // ------------------------------------------------------------------

    readonly property color colBg: palBg
    readonly property color colBgTransparent: "transparent"

    readonly property color colLabel: palDim      // "CPU", "MEM" - the noun
    readonly property color colValue: palFg       // 17%, 9.25G - the number
    readonly property color colFg: palFg
    readonly property color colBright: palBright
    readonly property color colDim: palDim
    readonly property color colMuted: palMuted
    readonly property color colFaint: palFaint
    readonly property color colBorder: palBorder

    readonly property color colAccent: palAccent  // active, connected, on
    readonly property color colAlert: palAlert    // muted, low battery, DND, VPN down
    readonly property color colWarn: palWarn      // state unknown / degraded
    readonly property color colOnAlert: palBg     // text sitting on an alert fill

    // The bar has no background of its own (see shell.qml), so text cannot
    // rely on a surface for contrast and carries its own dark outline. This
    // replaces the old same-colour halo, which added no contrast and only
    // faked extra weight while smearing the glyph edges.
    readonly property color colTextShadow: Qt.rgba(0, 0, 0, 0.55)

    // ------------------------------------------------------------------
    //  Per-widget roles
    // ------------------------------------------------------------------
    //  All of these deliberately collapse onto the ramp above. They stay
    //  as named properties so a widget can be re-tinted in one place if
    //  it ever earns its own emphasis - but the default is: no hue.

    readonly property color colClock: palFg
    readonly property color colCpu: palDim
    readonly property color colMem: palDim
    readonly property color colDisk: palDim
    readonly property color colVol: palFg
    readonly property color colNetwork: palDim
    readonly property color colBluetooth: palFg
    readonly property color colWindow: palDim     // window title is secondary info
    readonly property color colKernel: palDim

    readonly property color colWorkspaceActive: palBright
    readonly property color colWorkspaceInactive: palMuted

    // Unread badges: an unread message is an attention state, so it gets
    // the alert hue rather than a brand colour that would fight the rice.
    readonly property color colSlack: palAlert
    readonly property color colWhatsapp: palAlert

    // Font
    readonly property string fontFamily: "Terminess Nerd Font"
    readonly property int fontSize: 22
}
